const ADMIN_USER_ERROR_CODES = {
  NOT_FOUND: "ADMIN_USER_NOT_FOUND",
  SELF_ACTION_FORBIDDEN: "ADMIN_USER_SELF_ACTION_FORBIDDEN",
  SUSPENSION_REASON_REQUIRED: "ADMIN_USER_SUSPENSION_REASON_REQUIRED",
  ALREADY_SUSPENDED: "ADMIN_USER_ALREADY_SUSPENDED",
  ALREADY_ACTIVE: "ADMIN_USER_ALREADY_ACTIVE",
  STATUS_CONFLICT: "ADMIN_USER_STATUS_CONFLICT",
} as const;

export { ADMIN_USER_ERROR_CODES };
