const ADMIN_USER_ERROR_CODES = {
  NOT_FOUND: "ADMIN_USER_NOT_FOUND",
  SELF_ACTION_FORBIDDEN: "ADMIN_USER_SELF_ACTION_FORBIDDEN",
  SUSPENSION_REASON_REQUIRED: "ADMIN_USER_SUSPENSION_REASON_REQUIRED",
  ALREADY_SUSPENDED: "ADMIN_USER_ALREADY_SUSPENDED",
  ALREADY_ACTIVE: "ADMIN_USER_ALREADY_ACTIVE",
  STATUS_CONFLICT: "ADMIN_USER_STATUS_CONFLICT",
  ROLE_REASON_REQUIRED: "ADMIN_USER_ROLE_REASON_REQUIRED",
  ROLE_INVALID_TRANSITION: "ADMIN_USER_ROLE_INVALID_TRANSITION",
  ROLE_PROMOTION_REQUIRES_VERIFIED_EMAIL: "ADMIN_USER_ROLE_PROMOTION_REQUIRES_VERIFIED_EMAIL",
  ROLE_PROMOTION_REQUIRES_ACTIVE_ACCOUNT: "ADMIN_USER_ROLE_PROMOTION_REQUIRES_ACTIVE_ACCOUNT",
  ROLE_PROTECTED_ADMIN: "ADMIN_USER_ROLE_PROTECTED_ADMIN",
  ROLE_CONFLICT: "ADMIN_USER_ROLE_CONFLICT",
} as const;

const ADMIN_ENTRY_ERROR_CODES = {
  NOT_FOUND: "ADMIN_ENTRY_NOT_FOUND",
  INVALID_STATUS: "ADMIN_ENTRY_INVALID_STATUS",
  REASON_REQUIRED: "ADMIN_ENTRY_REASON_REQUIRED",
  ALREADY_ARCHIVED: "ADMIN_ENTRY_ALREADY_ARCHIVED",
  ALREADY_RESTORED: "ADMIN_ENTRY_ALREADY_RESTORED",
  LIFECYCLE_CONFLICT: "ADMIN_ENTRY_LIFECYCLE_CONFLICT",
} as const;

export { ADMIN_ENTRY_ERROR_CODES, ADMIN_USER_ERROR_CODES };
