const MODERATION_ERROR_CODES = {
  SUBMISSION_NOT_FOUND: "MODERATION_SUBMISSION_NOT_FOUND",
  SELF_APPROVAL_FORBIDDEN: "MODERATION_SELF_APPROVAL_FORBIDDEN",
  REASON_REQUIRED: "MODERATION_REASON_REQUIRED",
  ALREADY_DECIDED: "MODERATION_ALREADY_DECIDED",
  CONFLICT: "MODERATION_CONFLICT",
  CORRECTION_ENTRY_NOT_FOUND: "CORRECTION_ENTRY_NOT_FOUND",
  CORRECTION_NOT_FOUND: "CORRECTION_NOT_FOUND",
  CORRECTION_ALREADY_PENDING: "CORRECTION_ALREADY_PENDING",
  CORRECTION_ALREADY_DECIDED: "CORRECTION_ALREADY_DECIDED",
  CORRECTION_CONFLICT: "CORRECTION_CONFLICT",
  CORRECTION_SELF_REVIEW_FORBIDDEN: "CORRECTION_SELF_REVIEW_FORBIDDEN",
  CORRECTION_CONTENT_INVALID: "CORRECTION_CONTENT_INVALID",
  REPORT_TARGET_NOT_FOUND: "REPORT_TARGET_NOT_FOUND",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  REPORT_ALREADY_OPEN: "REPORT_ALREADY_OPEN",
  REPORT_ALREADY_RESOLVED: "REPORT_ALREADY_RESOLVED",
  REPORT_ACTION_INVALID: "REPORT_ACTION_INVALID",
  REPORT_CONFLICT: "REPORT_CONFLICT",
} as const;

export { MODERATION_ERROR_CODES };
