const MODERATION_ERROR_CODES = {
  SUBMISSION_NOT_FOUND: "MODERATION_SUBMISSION_NOT_FOUND",
  SELF_APPROVAL_FORBIDDEN: "MODERATION_SELF_APPROVAL_FORBIDDEN",
  REASON_REQUIRED: "MODERATION_REASON_REQUIRED",
  ALREADY_DECIDED: "MODERATION_ALREADY_DECIDED",
  CONFLICT: "MODERATION_CONFLICT",
} as const;

export { MODERATION_ERROR_CODES };
