const ENTRY_ERROR_CODES = {
  NOT_FOUND: "ENTRY_NOT_FOUND",
  NOT_OWNED: "ENTRY_NOT_OWNED",
  INVALID_STATUS: "ENTRY_INVALID_STATUS",
  TITLE_REQUIRED: "ENTRY_TITLE_REQUIRED",
  TAXONOMY_INVALID: "ENTRY_TAXONOMY_INVALID",
  DISTRICT_PROVINCE_MISMATCH: "ENTRY_DISTRICT_PROVINCE_MISMATCH",
  CONTENT_INVALID: "ENTRY_CONTENT_INVALID",
} as const;

export { ENTRY_ERROR_CODES };
