const ENTRY_ERROR_CODES = {
  NOT_FOUND: "ENTRY_NOT_FOUND",
  NOT_OWNED: "ENTRY_NOT_OWNED",
  INVALID_STATUS: "ENTRY_INVALID_STATUS",
  TITLE_REQUIRED: "ENTRY_TITLE_REQUIRED",
  TAXONOMY_INVALID: "ENTRY_TAXONOMY_INVALID",
  DISTRICT_PROVINCE_MISMATCH: "ENTRY_DISTRICT_PROVINCE_MISMATCH",
  CONTENT_INVALID: "ENTRY_CONTENT_INVALID",
  TAG_DUPLICATE: "ENTRY_TAG_DUPLICATE",
  TAG_INVALID: "ENTRY_TAG_INVALID",
  SOURCE_NOT_FOUND: "ENTRY_SOURCE_NOT_FOUND",
  SOURCE_INVALID: "ENTRY_SOURCE_INVALID",
  SOURCE_ORDER_DUPLICATE: "ENTRY_SOURCE_ORDER_DUPLICATE",
} as const;

export { ENTRY_ERROR_CODES };
