const IS_PUBLIC_ROUTE_KEY = "isPublicRoute";
const JWT_ACCESS_STRATEGY = "jwt";
const EMAIL_VERIFICATION_NEUTRAL_MESSAGE =
  "If the email can receive verification messages, a new verification email has been sent.";

const AUTH_ERROR_CODES = {
  EMAIL_ALREADY_REGISTERED: "AUTH_EMAIL_ALREADY_REGISTERED",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  PASSWORD_NOT_CONFIGURED: "AUTH_PASSWORD_NOT_CONFIGURED",
  VERIFICATION_TOKEN_INVALID: "AUTH_VERIFICATION_TOKEN_INVALID",
  VERIFICATION_TOKEN_EXPIRED: "AUTH_VERIFICATION_TOKEN_EXPIRED",
} as const;

export {
  AUTH_ERROR_CODES,
  EMAIL_VERIFICATION_NEUTRAL_MESSAGE,
  IS_PUBLIC_ROUTE_KEY,
  JWT_ACCESS_STRATEGY,
};
