const IS_PUBLIC_ROUTE_KEY = "isPublicRoute";
const JWT_ACCESS_STRATEGY = "jwt";
const GOOGLE_AUTH_STRATEGY = "google";
const FACEBOOK_AUTH_STRATEGY = "facebook";
const EMAIL_VERIFICATION_NEUTRAL_MESSAGE =
  "If the email can receive verification messages, a new verification email has been sent.";

const AUTH_ERROR_CODES = {
  EMAIL_ALREADY_REGISTERED: "AUTH_EMAIL_ALREADY_REGISTERED",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  PASSWORD_NOT_CONFIGURED: "AUTH_PASSWORD_NOT_CONFIGURED",
  VERIFICATION_TOKEN_INVALID: "AUTH_VERIFICATION_TOKEN_INVALID",
  VERIFICATION_TOKEN_EXPIRED: "AUTH_VERIFICATION_TOKEN_EXPIRED",
  GOOGLE_EMAIL_NOT_VERIFIED: "AUTH_GOOGLE_EMAIL_NOT_VERIFIED",
  GOOGLE_ACCOUNT_ALREADY_LINKED: "AUTH_GOOGLE_ACCOUNT_ALREADY_LINKED",
  GOOGLE_AUTH_FAILED: "AUTH_GOOGLE_AUTH_FAILED",
  FACEBOOK_EMAIL_REQUIRED: "AUTH_FACEBOOK_EMAIL_REQUIRED",
  FACEBOOK_EMAIL_LINKING_NOT_ALLOWED: "AUTH_FACEBOOK_EMAIL_LINKING_NOT_ALLOWED",
  FACEBOOK_ACCOUNT_ALREADY_LINKED: "AUTH_FACEBOOK_ACCOUNT_ALREADY_LINKED",
  FACEBOOK_AUTH_FAILED: "AUTH_FACEBOOK_AUTH_FAILED",
} as const;

export {
  AUTH_ERROR_CODES,
  EMAIL_VERIFICATION_NEUTRAL_MESSAGE,
  FACEBOOK_AUTH_STRATEGY,
  GOOGLE_AUTH_STRATEGY,
  IS_PUBLIC_ROUTE_KEY,
  JWT_ACCESS_STRATEGY,
};
