const TAXONOMY_ERROR_CODES = {
  DUPLICATE_NAME: "TAXONOMY_DUPLICATE_NAME",
  DUPLICATE_SLUG: "TAXONOMY_DUPLICATE_SLUG",
  INVALID_SLUG: "TAXONOMY_INVALID_SLUG",
  NOT_FOUND: "TAXONOMY_NOT_FOUND",
  PROVINCE_NOT_FOUND: "TAXONOMY_PROVINCE_NOT_FOUND",
  PROVINCE_IMAGE_NOT_FOUND: "TAXONOMY_PROVINCE_IMAGE_NOT_FOUND",
  PROVINCE_IMAGE_ALT_REQUIRED: "TAXONOMY_PROVINCE_IMAGE_ALT_REQUIRED",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  IMAGE_INVALID_TYPE: "IMAGE_INVALID_TYPE",
  INVALID_REORDER_ITEMS: "TAXONOMY_INVALID_REORDER_ITEMS",
} as const;

export { TAXONOMY_ERROR_CODES };
