const COMMUNITY_ERROR_CODES = {
  ENTRY_NOT_FOUND: "COMMUNITY_ENTRY_NOT_FOUND",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  COMMENT_BODY_INVALID: "COMMENT_BODY_INVALID",
  COMMENT_PARENT_INVALID: "COMMENT_PARENT_INVALID",
  COMMENT_PARENT_UNAVAILABLE: "COMMENT_PARENT_UNAVAILABLE",
  COMMENT_NOT_OWNED: "COMMENT_NOT_OWNED",
  COMMENT_UNAVAILABLE: "COMMENT_UNAVAILABLE",
  COMMENT_SELF_LIKE_FORBIDDEN: "COMMENT_SELF_LIKE_FORBIDDEN",
} as const;

export { COMMUNITY_ERROR_CODES };
