const COMMUNITY_ERROR_CODES = {
  ENTRY_NOT_FOUND: "COMMUNITY_ENTRY_NOT_FOUND",
  REVIEW_NOT_FOUND: "COMMUNITY_REVIEW_NOT_FOUND",
  REVIEW_BODY_INVALID: "COMMUNITY_REVIEW_BODY_INVALID",
  REVIEW_ALREADY_EXISTS: "COMMUNITY_REVIEW_ALREADY_EXISTS",
  RATING_INVALID: "COMMUNITY_RATING_INVALID",
} as const;

export { COMMUNITY_ERROR_CODES };
