import type { AdminAuditAction } from "@/features/admin/types/admin-audit";

const adminAuditActions = [
  "ENTRY_SUBMITTED",
  "ENTRY_APPROVED",
  "ENTRY_REJECTED",
  "ENTRY_CHANGES_REQUESTED",
  "ENTRY_HIDDEN",
  "ENTRY_ARCHIVED",
  "ENTRY_RESTORED",
  "ENTRY_REVISION_STARTED",
  "ENTRY_REVISION_REQUESTED",
  "ENTRY_REVISION_SUBMITTED",
  "ENTRY_REVISION_APPROVED",
  "ENTRY_REVISION_CHANGES_REQUESTED",
  "ENTRY_REVISION_REJECTED",
  "ENTRY_REVISION_CANCELLED",
  "CORRECTION_SUBMITTED",
  "CORRECTION_ACCEPTED",
  "CORRECTION_REJECTED",
  "REPORT_SUBMITTED",
  "REPORT_RESOLVED",
  "COMMENT_HIDDEN",
  "USER_ROLE_CHANGED",
  "USER_SUSPENDED",
  "USER_REACTIVATED",
  "USER_SESSIONS_REVOKED",
] as const satisfies readonly AdminAuditAction[];

const adminAuditMetadataLabels: Record<string, string> = {
  entryId: "شناسه مطلب",
  entryKey: "کلید مطلب",
  reviewId: "شناسه بررسی",
  versionNumber: "نسخه",
  oldStatus: "وضعیت پیشین",
  newStatus: "وضعیت جدید",
  authorId: "شناسه نویسنده",
  moderatorId: "شناسه ناظر",
  reason: "دلیل",
  revisionId: "شناسه ویرایش",
  baseVersionId: "نسخه پایه",
  correctionId: "شناسه پیشنهاد",
  section: "بخش",
  reportId: "شناسه گزارش",
  targetType: "نوع محتوا",
  resolutionAction: "نتیجه",
  notes: "یادداشت",
  commentId: "شناسه دیدگاه",
  previousStatus: "وضعیت پیشین حساب",
  revokedSessions: "نشست‌های پایان‌یافته",
  previousRole: "نقش پیشین",
  newRole: "نقش جدید",
};

export { adminAuditActions, adminAuditMetadataLabels };
