const PROFILE_ERROR_CODES = {
  DISPLAY_NAME_INVALID: "PROFILE_DISPLAY_NAME_INVALID",
  BIOGRAPHY_INVALID: "PROFILE_BIOGRAPHY_INVALID",
  IMAGE_INVALID_TYPE: "PROFILE_IMAGE_INVALID_TYPE",
  IMAGE_TOO_LARGE: "PROFILE_IMAGE_TOO_LARGE",
  CULTURAL_INTEREST_INVALID: "PROFILE_CULTURAL_INTEREST_INVALID",
  PROVINCE_INVALID: "PROFILE_PROVINCE_INVALID",
  BOOKMARK_ENTRY_NOT_FOUND: "PROFILE_BOOKMARK_ENTRY_NOT_FOUND",
  BOOKMARK_NOT_FOUND: "PROFILE_BOOKMARK_NOT_FOUND",
  QUERY_INVALID: "PROFILE_QUERY_INVALID",
} as const;

export { PROFILE_ERROR_CODES };
